version: 2

models:
  - name: fct_messages
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_key
        tests:
          - not_null
      - name: date_key
        tests:
          - not_null

  - name: dim_dates
    columns:
      - name: date_key
        tests:
          - unique
          - not_null
